### ISSUE TITLE
 es.indices.exists not work

### ISSUE THREAD

**Issue by ProgRoman** [brandomr/spark-es#1]
I ran everything according to the instructions. But when running
Spark-ES.ipynb
an error occurs when is performed
#if the stream-test index exists, wipe it out and create a new one
if es.indices.exists ('stream-test'):
by doing
es = Elasticsearch ('elasticsearch: 9200')
everything is fine, and then on es.indices.exists ... falls error

> ConnectionError: ConnectionError (<urllib3.connection.HTTPConnection object at 0x7f0efd10a6a0>: Failed to establish a new connection: [Errno-3] Temporary failure in name resolution) caused by: NewConnectionError (<urllib3.connection.HTTPConnection object at 0x7f0efd10a6a0>: Failed to establish a new connection: [Errno-3] Temporary failure in name resolution)

the following is written in the terminal:

kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:15Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:15Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:15Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:15Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:15Z","tags":["status","plugin:ml@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - No Living connections","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:ml@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"No Living connections"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:xpack_main@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:graph@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:reporting@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:security@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:searchprofiler@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:tilemap@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:watcher@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:upgrade@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["status","plugin:elasticsearch@5.6.1","error"],"pid":1,"state":"red","message":"Status changed from red to red - Request Timeout after 3000ms","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana-node      | {"type":"log","@timestamp":"2018-07-05T07:30:21Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}

how to fix

**Comment by brandomr** [comment]
Hi @ProgRoman it sounds like your Elasticsearch container is not running. Can you share logs from the Elasticsearch container? 

I ran into this issue if I did not adjust the memory allowed for Docker and ES would fail due to its memory intensive requirements. 

Let me know if you can share the ES logs.

**Comment by ProgRoman** [comment]
problem solved
1. the deploy section was not supported
just deleted it
2. volumes:
       - ./volumes/es:/usr/share/elasticsearch/data
created a folder with invalid rights, created the folder and everything worked

**Comment by brandomr** [comment]
Awesome! If you're interested, I have even more examples in my book (primarily with Spark Streaming running in Docker): [Real Time Crypto](http://realtimecrypto.io/). Shameless plug!
