### ISSUE TITLE
sc.newAPIHadoopRDD falls with an error

### ISSUE THREAD

**Issue by ProgRoman** [brandomr/spark-es#2]
Performed all the cells sequentially in the Spark-ES.ipynb, before this cell everything was completed
```
es_read_conf = { 
    # specify the node that we are sending data to (this should be the master)    
    "es.nodes" : "elasticsearch",
    
    # specify the read resource in the format 'index/doc-type'
    "es.resource" : "stream-test/sample"
    }

es_rdd = sc.newAPIHadoopRDD(
    inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
    keyClass="org.apache.hadoop.io.NullWritable", 
    valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", 
    conf=es_read_conf)
```
after execution output such an error

> ---------------------------------------------------------------------------
> Py4JJavaError                             Traceback (most recent call last)
> <ipython-input-41-55396f76ff48> in <module>()
>      11     keyClass="org.apache.hadoop.io.NullWritable",
>      12     valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
> ---> 13     conf=es_read_conf)
> 
> /usr/local/spark/python/pyspark/context.py in newAPIHadoopRDD(self, inputFormatClass, keyClass, valueClass, keyConverter, valueConverter, conf, batchSize)
>     715         jrdd = self._jvm.PythonRDD.newAPIHadoopRDD(self._jsc, inputFormatClass, keyClass,
>     716                                                    valueClass, keyConverter, valueConverter,
> --> 717                                                    jconf, batchSize)
>     718         return RDD(jrdd, self)
>     719 
> 
> /usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
>    1255         answer = self.gateway_client.send_command(command)
>    1256         return_value = get_return_value(
> -> 1257             answer, self.gateway_client, self.target_id, self.name)
>    1258 
>    1259         for temp_arg in temp_args:
> 
> /usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
>     326                 raise Py4JJavaError(
>     327                     "An error occurred while calling {0}{1}{2}.\n".
> --> 328                     format(target_id, ".", name), value)
>     329             else:
>     330                 raise Py4JError(
> 
> Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
> : org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Index [stream-test/sample] missing and settings [es.index.read.missing.as.empty] is set to false
> 	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:238)
> 	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:405)
> 	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:386)
> 	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:127)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
> 	at scala.Option.getOrElse(Option.scala:121)
> 	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
> 	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
> 	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
> 	at scala.Option.getOrElse(Option.scala:121)
> 	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
> 	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1337)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
> 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
> 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
> 	at org.apache.spark.rdd.RDD.take(RDD.scala:1331)
> 	at org.apache.spark.api.python.SerDeUtil$.pairRDDToPython(SerDeUtil.scala:239)
> 	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:291)
> 	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 	at py4j.Gateway.invoke(Gateway.java:282)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by brandomr** [comment]
It looks like you might not have created the index `stream-test` based on the error that is thrown:

```
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Index [stream-test/sample] missing and settings [es.index.read.missing.as.empty] is set to false
```

Also, ES has pretty much deprecated `doc_types` (in this case `sample`) so it may be that you should not be specifying the `doc_type` anymore. 

Can you check that the index exists? Perhaps try indexing an empty document of `doc_type` `sample` so that there is a mapping for that `doc_type` (then delete the document). Then try the indexing job.

**Comment by ProgRoman** [comment]
strange, but after restarting it all works.
